repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -  id: black
       language: python
       verbose: true
       name: black
       entry: bash -c "black . --config=pyproject.toml"
    -  id: flake8
       language: python
       verbose: true
       name: flake8
       entry: bash -c "flake8 . --config=.flake8"
